### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by birkir** [fika-community/prism#2]
I am not sure from the docs, but how does the library compare to styled components, inline styles etc. in terms of performance?

Does it use React Native's StyleSheet API internally to minimize data flow on the bridge?

**Comment by tmpfs** [comment]
Hey @birkir,

Indeed, really it is a thin wrapper for the RN stylesheet API that performs style lookup. Overhead should be fairly minimal provided stylesheets are not flattened.

Components are registered initially so that `styleOptions` can be configured on the HOC, so when `Prism.configure` is called it is O(N) where N is the number of components being wrapped.

I have not done any benchmarks but I created this in a couple of weeks as part of a bigger real world RN app and anecdotally the performance seems reasonable.

Let me know if you run into any issues and I will take a look.

**Comment by tmpfs** [comment]
Also you probably want to read the last sections of the readme:

https://github.com/tmpfs/prism/blob/master/README.md#pure-mode


https://github.com/tmpfs/prism/blob/master/README.md#performance

**Comment by tmpfs** [comment]
Closing as not an issue until somebody reports performance problems.
